# Site Settings
locale                   : "en-US"
title                    : "Talha Omer's Personal Website"
name                     : "Talha Omer"
description              : "Doctoral candidate in Statistics at Jönköping University."
url                      : "https://talhaomer472.github.io"
baseurl                  : ""
repository               : "talhaomer472/talhaomer472.github.io"
logo                     : "/assets/images/logo.png"

# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"

# Site Author
author:
  name             : "Talha Omer"
  avatar           : "/assets/images/My picture.jpeg"
  bio              : "Doctoral candidate in Statistics at Jönköping University."
  location         : "Jönköping, Sweden"
  email            : "talha.omer@ju.se"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:talha.omer@ju.se"
    - label: "Personal Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:talhaomer472@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=la_b0isAAAAJ&hl=en&oi=sra"
    - label: "ResearchGate"
      icon: "fas fa-fw fa-book"
      url: "https://www.researchgate.net/profile/Talha-Omer"
    - label: "University Profile"
      icon: "fas fa-fw fa-university"
      url: "https://ju.se/personinfo.html?id=3695"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/talha-omer-b4a803196/"

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "Research Publications"
    url: "/research-publications/"
  - title: "Working Papers"
    url: "/working-papers/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Codes"
    url: "/codes/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Markdown Processing
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:categories/:title/
timezone: Europe/Stockholm

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/
