# Site Settings
title: "Talha Omer's Personal Website"
description: "Doctoral candidate in Statistics at Jönköping University."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://talhaomer472.github.io" # the base hostname & protocol for your site

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Site Author
author:
  name: "Talha Omer"
  avatar: "/assets/images/Mypic.jpeg"
  bio: "Doctoral candidate in Statistics at Jönköping University."
  location: "Jönköping, Sweden"
  email: "talha.omer@ju.se"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:talha.omer@ju.se"
    - label: "Personal Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:talhaomer472@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=la_b0isAAAAJ&hl=en&oi=sra"
    - label: "ResearchGate"
      icon: "fas fa-fw fa-book"
      url: "https://www.researchgate.net/profile/Talha-Omer"
    - label: "University Profile"
      icon: "fas fa-fw fa-university"
      url: "https://ju.se/personinfo.html?id=3695"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/talha-omer-b4a803196/"

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "Research Publications"
    url: "/research-publications/"
  - title: "Working Papers"
    url: "/working-papers/"
  - title: "Teaching"
    url: "/teaching/"
  - title: "Codes"
    url: "/codes/"
